name: chat_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  kiwi: ^4.0.3
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  bot_toast: ^4.0.3
  flutter_secure_storage: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  animated_theme_switcher: ^2.0.7
  freezed: ^2.2.1

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.1.4
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/yb_thin.ttf
          weight: 100
        - asset: assets/fonts/yb_light.ttf
          weight: 300
        - asset: assets/fonts/yb_regular.ttf
          weight: 400
        - asset: assets/fonts/yb_medium.ttf
          weight: 500
        - asset: assets/fonts/yb_semiBold.ttf
          weight: 600
        - asset: assets/fonts/yb_bold.ttf
          weight: 700
        - asset: assets/fonts/yb_extraBold.ttf
          weight: 800
        - asset: assets/fonts/yb_black.ttf
          weight: 900

    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_light.ttf
          weight: 200
        - asset: assets/fonts/gilroy_light.ttf
          weight: 300
        - asset: assets/fonts/gilroy_regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy_medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy_semibold.ttf
          weight: 600
        - asset: assets/fonts/gilroy_bold.ttf
          weight: 700
